export const SHOW_ADD_EDIT_MODAL = "SHOW_ADD_EDIT_MODAL";
export const HIDE_ADD_EDIT_MODAL = "HIDE_ADD_EDIT_MODAL";
export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL";
export const HIDE_DELETE_MODAL = "HIDE_DELETE_MODAL";
